### ISSUE TITLE
Auto-reply sending to wrong email

### ISSUE THREAD

**Issue by dathwa** [GrofGraf/octobercms-contact-form#4]
Hi Grof.
A curious thing when using the auto-reply feature.
It send both emails to the Settings::get('email') address.

I added a trace_log to the function below and post('email) IS correct, so it SHOULD work.
But it seems to cache the first email address and re-uses for sending the 2nd email.

Any idea why this might be?
Thanks for a cool plugin.

`Mail::send('grofgraf.contactme::emails.auto-reply', array_merge(post(), array('auto_reply' => $html)), function($m){
        $test = post();
        trace_log($test);
        $m->to(post('email'), post('name'))
          ->subject(Settings::instance()->auto_reply_subject);
        if(Settings::get('enable_auto_reply_attachment') && Input::file('attachment')){
          $m->attach(Input::file('attachment'));
        }
      });`

**Comment by GrofGraf** [comment]
Hi @dathwa  , thank you for your comment.
Actually I am tweaking a plugin just now, because I need some extra features for my projects.
I am expecting to push a new update by the end of the day.
I will also take a look at the problem you described.

**Comment by dathwa** [comment]
Hi Grof.
I've figured out what the problem was.
My mistake. In my config/mail.php I had ALL mail set to go to my own email.
`'to' => [
     'address' => 'me@example.com',
     'name' => 'Me'
],`
Your plugin is perfect. 
Thanks again.
